# Generated by Django 4.2.13 on 2024-05-12 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSquad',
            fields=[
                ('squad_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.IntegerField()),
                ('player_username', models.CharField(max_length=50)),
                ('position_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('contract_start', models.DateField()),
                ('contract_finish', models.DateField()),
                ('channel_id', models.CharField(max_length=50)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volleyball.coach')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyball.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyball.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyball.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyball.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volleyball.user'),
        ),
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('stadium_id', models.IntegerField()),
                ('time_slot', models.IntegerField()),
                ('date', models.DateField()),
                ('rating', models.FloatField(null=True)),
                ('assigned_jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='volleyball.jury')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyball.team')),
            ],
        ),
        migrations.AddField(
            model_name='jury',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volleyball.user'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volleyball.user'),
        ),
    ]
