# Generated by Django 4.2.13 on 2024-05-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
        migrations.DeleteModel(
            name='DatabaseManager',
        ),
        migrations.RemoveField(
            model_name='jury',
            name='user',
        ),
        migrations.RemoveField(
            model_name='matchsession',
            name='assigned_jury',
        ),
        migrations.RemoveField(
            model_name='matchsession',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playerposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='playerposition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playerteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerteam',
            name='user',
        ),
        migrations.DeleteModel(
            name='SessionSquad',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Jury',
        ),
        migrations.DeleteModel(
            name='MatchSession',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerPosition',
        ),
        migrations.DeleteModel(
            name='PlayerTeam',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
